apiVersion: v1
kind: ConfigMap
metadata:
  name: opencloud-config
  namespace: opencloud
data:
  OC_URL: "https://opencloud.jtanprojects.com"      # public URL — must be https even in HTTP mode
  IDM_URL: "https://opencloud.jtanprojects.com"      # same domain
  IDM_ADMIN_USERNAME: "admin"
  OC_INSECURE: "true"                            # allows internal OIDC calls over HTTP
  PROXY_SKIP_VERIFY_TLS: "true"                  # skips TLS verification on internal calls
