apiVersion: v1
apiVersion: v1
kind: ConfigMap
metadata:
  name: opencloud-config
  namespace: opencloud
data:
  IDM_ADMIN_USERNAME: admin
  IDM_URL: https://opencloud.jtanprojects.com
  OC_URL: https://opencloud.jtanprojects.com
  PROXY_HTTPS_ADDR: 0.0.0.0:9200
  PROXY_TLS_CERT: /certs/server.pem
  PROXY_TLS_KEY: /certs/server.key
  OC_INSECURE: "true"
  PROXY_SKIP_VERIFY_TLS: "true"
