apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opencloud-config
  namespace: opencloud
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: opencloud-tank-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: tank
  hostPath:
    path: /tank
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opencloud-tank
  namespace: opencloud
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: tank
  resources:
    requests:
      storage: 500Gi
  volumeName: opencloud-tank-pv
