apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-tank-pv
spec:
  capacity:
    storage: 900Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: tank
  hostPath:
    path: /tank/nextcloud-data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: tank
  resources:
    requests:
      storage: 900Gi
  volumeName: nextcloud-tank-pv
