apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  cloud.override: |
    rewrite name opencloud.jtanprojects.com nginx-gateway-nginx.gateway-system.svc.cluster.local
    rewrite name nextcloud.jtanprojects.com nginx-gateway-nginx.gateway-system.svc.cluster.local
