apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fitness
  template:
    metadata:
      labels:
        app: fitness
    spec:
      containers:
        - name: fitness
          image: jtandockerhub/react-test-app:v1.1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: fitness
  namespace: default
spec:
  selector:
    app: fitness
  ports:
    - port: 80
      targetPort: 3000
