## TODO move this to scecrets later
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
type: Opaque
stringData:
  # The key name MUST match what the ClusterIssuer expects.
  # We'll use "api-token" (the standard for Cloudflare API tokens).
  api-token: <cloudflare-api-token>
