apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
  namespace: nextcloud
type: Opaque
stringData:
  nextcloud-username: admin
  nextcloud-password: "changeme"
  db-username: "nextcloud"
  db-password: "changeme-db"
  redis-password: "changeme-redis"
