apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: opencloud
data:
  nginx.conf: |
    events {}
    http {
        server {
            listen 80;
            server_name opencloud.jtanprojects.com;

            location / {
                proxy_pass              https://opencloud:9200;
                proxy_set_header        Host $host;
                proxy_set_header        X-Real-IP $remote_addr;
                proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header        X-Forwarded-Proto https;    # tell opencloud it's HTTPS
                proxy_ssl_verify        off;
            }
        }
    }
