apiVersion: v1
kind: Secret
metadata:
  name: opencloud-secret
  namespace: opencloud
type: Opaque
stringData:
  # This is the easiest way - values are base64 encoded automatically
  JWT_SECRET: "create your own jwt secret here"
  IDM_ADMIN_PASSWORD: "yourownpassword"
